### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by WhirlFirst**
1.update database of processing 
2.api of date and formula
3.random seed is current day now.

### CODE REVIEW

**Comment by huangy10** [comment]
Please add a .gitignore file to ignore files in .idea and .pyc files.

**Comment by huangy10** [comment]
I've checked your latest commit. Although you have those files added to .gitignore file, they still exist in the tracking cache. Remove them by run command `git rm --cached filename`

**Comment by WhirlFirst** [comment]
completed

**Comment by WhirlFirst** [comment]
@huangy10  
I add a personal html to learn to use css&js in Django. I have tested it on my own computer. it works.

And I have also uploaded requirement already.

**Comment by huangy10** [comment]
@WhirlFirst Good job. Have you finished your exams?

**Pull request merged**
